### PR TITLE
Fix link parsing for new versions

### PR DESCRIPTION
**Pull request by tovam**
This fixes the parsing of the deb links in https://kernel.ubuntu.com/~kernel-ppa/mainline/xxx/
#43

### CODE REVIEW

**Comment by tovam** [comment]
I added the version in the 'invalid' files so that invalidating them only requires releasing a new version and not manual cache cleaning

**Comment by kaincenteno** [comment]
looking forward for this PR to be merged as new Ryzen laptops need the new kernel.

Thanks for your work =)

**Comment by StatusCode404** [comment]
Hi All, any update on the review of this PR?  What's the hold-up?

**Comment by kaincenteno** [comment]
@StatusCode404 it might be the holidays, just give the developer time :cat:

**Comment by noah1510** [comment]
@bkw777 @tovam It seems that the changes button is now broken for the new links, I cannot click on the changes button for any kernel newer that 5.7.2, can you confirm this behavior?

**Pull request merged**
