### PR TITLE
Update uk.po

### PR DESCRIPTION
**Pull request by cappelikan**

### CODE REVIEW

**Comment by bkw777** [comment]
Does the way I edited it still make sense?

**Comment by cappelikan** [comment]
> "y" and "n" are not words, they are single letter anwers to y/n prompts. They should be a single letter, and should match the y/n prompts, and should be whatever letter the user actually types. Please look at lines 190, 199, 705, & 709, and make them all agree with each other so that the prompts mach the key press, and please preserve the capitalization also because that indicates the default, if you would not mind.

Ok

**Comment by cappelikan** [comment]
> Имеет ли смысл то, как я его редактировал?

Mayby yes , i wanted to clarify this issue , there is a string msgid ""
msgid ""
"Copies the entire output buffer, including scrollback, to the clipboard."
msgstr ""
"Копіює весь вихідний буфер, включаючи прокручування, до буфера обміну."

At the output I get

msgid ""
"Copies the entire output buffer, including scrollback, to the clipboard."
msgstr "Копіює весь вихідний буфер, включаючи прокручування, до буфера обміну."

when I postpone the deadline as in the original, there is a constant correction, what am I doing wrong?

**Comment by bkw777** [comment]
These two are equivalent.
```
msgstr ""
"..."
```
```
msgstr "..."
```

Just when msgmerge re-writes the .po file it reformats to break up long lines into multiple shorter lines, and the first part is always "". So,  
msgstr "really........ long............. line.............."  
gets re-written as  
msgstr ""
"really..........."
"long............"
"line.........."

The invalid syntax was the << >> quote characters, and one time there was a "." outside of the quotes.

**Comment by cappelikan** [comment]
> These two are equivalent.
> 
> ```
> msgstr ""
> "..."
> ```
> 
> ```
> msgstr "..."
> ```
> 
> Just when msgmerge re-writes the .po file it reformats to break up long lines into multiple shorter lines, and the first part is always "". So, msgstr "really........ long............. line.............." gets re-written as msgstr "" "really..........." "long............" "line.........."
> 
> The invalid syntax was the << >> quote characters, and one time there was a "." outside of the quotes.

I write 
msgid ""
"Copies the entire output buffer, including scrollback, to the clipboard."
msgstr "Копіює весь вихідний буфер, включаючи прокручування, до буфера обміну."
and msgstr "" 
msgstr "Копіює весь вихідний буфер, включаючи прокручування, до буфера обміну."
forcefully transform to 
msgid ""
"Copies the entire output buffer, including scrollback, to the clipboard."
msgstr "Копіює весь вихідний буфер, включаючи прокручування, до буфера обміну."
I seem to be doing everything right, I don’t understand how.

**Comment by bkw777** [comment]
I don't think that's a problem. It's just two equal ways to format the same thing.
On my machine when I run "make" my copy of msgmerge seems to always re-write to output the multi-line style. But it doesn't matter. Both forms are valid. It probably has to do with default options in different versions of msgmerge or some other .po utility. I think don't worry about that. Not a problem.

Or if you are asking how it happens, during "make", xgettext reads all the source files and outputs the .pot file,
then msgmerge reads both the .pot file and the .po file and updates the .po file. So the final contents of the .po file are determined by msgmerge.

That formatting difference is not what I meant by invalid syntax. The invalid syntax was  
«Команда, яка використовується для запуску dpkg із правами root.\n»  («» are not valid quote characters in .po files)  
the fixc was  
"Команда, яка використовується для запуску dpkg із правами root.\n"  

and  
"Відредагуйте команду, щоб налаштувати зовнішній вигляд терміналу".   (text outside of quotes)  
the fix was  
"Відредагуйте команду, щоб налаштувати зовнішній вигляд терміналу."

And those were on other commits not this one. In this commit I was only talking about the full words for Yes  and No where it was intended to be just the first letters for the users answer to a prompt. No need to make the user type out "Yes" just to agree to proceed.

**Comment by cappelikan** [comment]
> And those were on other commits not this one. In this commit I was only talking about the full words for Yes and No where it was intended to be just the first letters for the users answer to a prompt. No need to make the user type out "Yes" just to agree to proceed.
Well, let it be

**Pull request merged**
