### PR TITLE
Update Turkish translation

### PR DESCRIPTION
**Pull request by sabriunal**

### CODE REVIEW

**Review by bkw777 — CHANGES_REQUESTED** [review]
remove messages.mo please, otherwise looks good

**Comment by sabriunal** [comment]
> remove messages.mo please, otherwise looks good

Already removed :+1:

**Comment by bkw777** [comment]
I meant remove the file from the pr, not remove the file from the repo.
You have a pr that still wants to change the file, by deleting it.
Perhaps try this, (untested, may not be fully correct):
```
git checkout update-tr
git checkout master po/messages.mo
git commit --amend --no-edit
git push -f
```
Then the pr should no longer include the file since your copy won't be different from mine.

**Comment by sabriunal** [comment]
Okay. Fixed.

**Comment by bkw777** [comment]
perfect, thanks buddy

**Pull request merged**
