### PR TITLE
fixed command on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by Goddard**
Fixed the command on newer version.  Now compiles on ubuntu 20.04.

### CODE REVIEW

**Comment by bkw777** [comment]
This doesn't seem right to me. Shouldn't it depend on #if GLIB_LT_2_58 or similar?

**Comment by bkw777** [comment]
It already compiled on 20.04 since January
https://github.com/bkw777/mainline/commit/73c60bcd2562294931bf8234ebee25fe92cb751a
So is it really something else like the vala version or Glib versions or something?

**Comment by Goddard** [comment]
I'm not 100% sure.  It wouldn't compile for me.  I made this change and it compiled.  That is as far as  I went with it.

**Comment by bkw777** [comment]
This does not build for me, so it's only right in some condition, and the condition needs to be figured out and expressed.

`src/Gtk/TerminalWindow.vala:208.19-208.45: error: Argument 1: Cannot convert from 'unowned uint8[]' to 'unowned char[]?'
                term.feed_child("%s\n".printf(command).data);
`

**Comment by Goddard** [comment]
maybe version 2.9.0 vs 2.9.1?

**Comment by bkw777** [comment]
What does `pkg-config glib-2.0` say on your box?

**Comment by bkw777** [comment]
guys... check it out...
`
$ grep -nHIirF -- "execute_command"
src/Gtk/TerminalWindow.vala:205:        public void execute_command(string command){
$
`
We aren't even USING that function anywhere. We can just remove the whole thing and the junk I added to Makefile to check the Glib version.
I just tried it, it built and ran, including the terminal window for installing/removing.

**Comment by bkw777** [comment]
Fixed in https://github.com/bkw777/mainline/commit/7c9681af73e5fa02439503f5089b2e9abd73198d

**Pull request closed without merging**
