### PR TITLE
Moving to GtkHeaderbar

### PR DESCRIPTION
**Pull request by mirkobrombin**
Hoping to be useful, I implemented the GtkHeaderbar widget to match with other GTK applications and make the UI (I hope) more intuitive.

Screenshot from 2021-04-10 13-11-18

### CODE REVIEW

**Comment by bkw777** [comment]
What is the intended porpose of this change, and where did the install/remove/etc buttons go?

**Comment by mirkobrombin** [comment]
UI components:
hig

The intended purpose: 
> I implemented the GtkHeaderbar widget **to match with other GTK applications and make the UI (I hope) more intuitive.**

**Comment by bkw777** [comment]
I like about half of this.

I don't find some of the icons more intuitive than the text they replaced. In fact I somehow didn't even notice that there were even any clickable controls at all untill you pointed them out so explicitly. Being embedded in the titlebar makes me ignore them as though they were window control widgets and not part of the app.

But, if most other apps are going this way, then it will be more intuitive to other people who are used to those other apps, and I do like anything that uses less screen real-estate.

I'll have to convince myself to like it. I probably will end up going with it.

Thanks much!

**Comment by mirkobrombin** [comment]
> I like about half of this.
> 
> I don't find some of the icons more intuitive than the text they replaced. In fact I somehow didn't even notice that there were even any clickable controls at all untill you pointed them out so explicitly. Being embedded in the titlebar makes me ignore them as though they were window control widgets and not part of the app.
> 
> But, if most other apps are going this way, then it will be more intuitive to other people who are used to those other apps, and I do like anything that uses less screen real-estate.
> 
> I'll have to convince myself to like it. I probably will end up going with it.
> 
> Thanks much!

Can it help if I tell you that when you hover over a button, the tooltip with the old title appears?

**Pull request closed without merging**
