### PR TITLE
Introduce FileDownloader and lazily download changelogs

### PR DESCRIPTION
**Pull request by LucasChollet**
PR of the week :smile:

On `FileDownloader` (more details in the commit message):
This utility aims to be part of a replacement system for `DownloadManager`. In fact, the latter suffer from multiple flaws as its unnecessary complexity, dependence over an external tool and its design forcing the user to busy-wait.

Also, with lazy downloads of changelogs, a cold start (with an empty `.cache`) now takes 50% less times on my computer. Dropping from 36 to only 18 seconds.

As usual, it comes with it batch of code removal and overall improvements.

On a side note, have you ever considered the "rebase and merge" option instead of a classic merge? IMO, merge commits tends to really bloat the git history.

### CODE REVIEW

**Comment by bkw777** [comment]
I like all of this. Testing.

**Comment by LucasChollet** [comment]
Hmm after writing #182 I realized something.
If downloading the changelogs fails, it displays the error returned by `File.copy()`. Should I call `if(!can_reach_mainline_ppa()) return;` to display the "No Internet" dialog before trying to download?

It won't be as meaningful as the `File.copy()` error, but at least consistent all over the place. We can also do it the other way around and display underlying errors once we fully dropped the usage of `aria2c`.

Let me know what you prefer

**Comment by bkw777** [comment]
If you're gunning for complete reemoval of aria2c and don't see any real problem, then the exact error message during a transition period doesn't matter much. I say don't worry about the polish until the meat changes are done.

**Comment by LucasChollet** [comment]
On one hand, I don't really care if we should display detailed messages or not. I mean, if something is going wrong with this app, I can always look at the code and figure it out. So it depends more on your policy on user experience, that being said I would slightly prefer detailed errors as they are common to every gnome software and "not wrong" (as an example, if the computer is indeed connected to the internet but the ppa is down).

On the other hand, I would like that each of my contribution only enhance mainline and degrading consistency is not something I'm happy with. Especially if we can get it right on the first try. So I guess it depends more on your choice. Anyway, If you prefer detailed messages you can merge this, and I will slightly modify #182. Or if you prefer the "No internet" dialog, merge #182, and I only have to add two lines here.

**Comment by LucasChollet** [comment]
My hack to capture `bool` by reference wasn't needed, so I removed it

**Comment by bkw777** [comment]
I don't like messages to say things they don't actually know in the interests of being simpler. If all we know is that an http transaction failed, then I'd rather say that than say the net is down or that kernel.ubuntu is down.
I like to include whatever essential details make the message actionable. For instance, the full url that was tried, so that the user could grab it and try manually in a browser. The extra detail is ok because the entire event is supposed to be the exception not the rule. "Failed to download https://..." maybe with whatever errno we might have from the underlying call, like a file copy error the errno might indicate it's a permissions problem which is way more helpful to know than not.

But that's also all polish. I'm ok with not trying to polish too much while stuff is still changing. It doesn't break the app if an error message isn't ideal for a few commits.

**Comment by LucasChollet** [comment]
Sure, so I guess this is ready to merge.

And if you want me to add the errno and error domain to the dialog, I will do it in another PR when I will get rid of `aria2c` so I can factorize and homogenize all error messages.

**Comment by bkw777** [comment]
Users are reporting problems https://github.com/bkw777/mainline/issues/190

**Pull request merged**
