### PR TITLE
Remove busy-waiting to update the "Refreshing" dialog

### PR DESCRIPTION
**Pull request by LucasChollet**
No intentional behavior changes are included in this PR.

This is a simple refactor to support future improvements.

It also cleans-up some unused functions.

### CODE REVIEW

**Comment by bkw777** [comment]
looks nice. trying it for a bit.

**Comment by bkw777** [comment]
does not work for me. window just exits after a second.
.. .and then after a few more tries it works normally.
I can't debug because now it's working. I think maybe it didn't handle a network issue well?
It failed a few times, then I tried from a terminal and it hung during refreshing instead of exiting, then when I tried with debug it worked, and now it works from the desktop menu too. So it was a transient.

I will have to try to make it fail with artificial network problem and verify if the existing version behaves any differently. If the old version exits the same way, then there's no regression. But it never just exits like that. Usually if there's a network problem and the index download fails, it just displays an empty kernel list, or only the installed kernels.

**Comment by bkw777** [comment]
ouch, also exited after installing a kernel instead of refreshing the kernel list

**Comment by LucasChollet** [comment]
Sorry for that, it works fine on my machine :shrug:

To replicate it, have you tried to remove `.cache/mainline`? I know that it used to make things worse when I was testing it.

**Comment by bkw777** [comment]
Uninstalled the kernel that I just installed, the uninstall seemed to go normally, after closing the dpkg window it refreshed the list and exited, looks like right at the end of the refresh. This time I got some output from --debug

`
bkw@fw:~/src/mainline$ mainline-gtk --debug
mainline 1.0.18
Distribution: Ubuntu 22.04.1 LTS
Architecture: amd64
Running kernel: 6.1.8-060108-generic
D: tv_refresh()

[...]

D: check_updates()
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
mainline-gtk: ../../src/xcb_io.c:175: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted (core dumped)
bkw@fw:~/src/mainline$ 
`

**Comment by LucasChollet** [comment]
Ok, let me have a look at it
And let's add GitHub actions to at least smoke test `mainline`

**Comment by LucasChollet** [comment]
Are you using X11? `xcb` seems related to X11, and I'm on Wayland, so it would explain the difference.

**Comment by bkw777** [comment]
xubuntu & xfce, so yes X

**Comment by LucasChollet** [comment]
I didn't test it, but I guess that it should be resolved.
I'm currently installing X11 though.

Side note: I slightly modified the second commit to catch more errors.

**Comment by LucasChollet** [comment]
Even with X11, I'm unable to reproduce the crash.
Let me know if the issue persists.

**Comment by bkw777** [comment]
I can't tell if this is really the right way to fix this but is seems wrong. I hate vala. Or parhaps just the docs.
When I try to google for vala threads, I just get a doc sayds how to use thread.create like it already had in there.
https://naaando.gitbooks.io/the-vala-tutorial/content/en/5-advanced-features/5.2-multi-threading/threads-in-vala.html
Why does it need using X, and --pkg x11 now when it never did before? I understand it's because of calling X.foo, but what I mean is why didn't it always need that since day one?

**Comment by LucasChollet** [comment]
> I hate vala. Or parhaps just the docs.

In my humble experience, don't google Vala specific question other than syntax related, always refer to the C implementation. It's much more documented.

> Why didn't it always need that since day one?

We used to update GTK widgets on the main thread, which is good as GTK is not thread safe. But it was at the cost of quirks, probably race conditions (and obviously `sleep`s but I don't even want to talk about it :sweat_smile:). Now that we call a callback in the worker thread, it is needed to ensure that the event is still scheduled on the main thread's event loop. That's why we call [`Gdk.threads_add_idle_full`](https://docs.gtk.org/gdk3/func.threads_add_idle_full.html), which takes care of locking the GDK lock. Now, an educated guess: it also needs Xlib's mutexes or make `xcb` call that need them to be initialized by `XInitThreads()`. I updated the commit message with more explanations.

Also, as a flaky note, many Gtk 2 or 3 applications call it in main. You can find multiple examples by looking at `XInitThreads()` occurrences on GitHub. So I guess it won't hurt much.

Did you receive my email? (sent the 28)

**Comment by bkw777** [comment]
So far so good.  This is great. Thanks much!

**Pull request merged**
